export const partnersData = [
  {
    id: 1,
    order: 1,
    name: "Momentify",
    details: "Brand, Web, Product",
    year: 2024,
    image: "https://framerusercontent.com/images/WtDkhEjQ1TNDVDYNkBVhFoJnfU.jpg?scale-down-to=1024",
  },
  {
    id: 2,
    order: 2,
    name: "Norby",
    details: "Motion",
    year: 2025,
    image: "https://framerusercontent.com/images/WtDkhEjQ1TNDVDYNkBVhFoJnfU.jpg?scale-down-to=1024",
  },
  {
    id: 3,
    order: 3,
    name: "Spark",
    details: "Brand, Web, Product",
    year: 2024,
    image: "https://framerusercontent.com/images/5z0ZyBUqdAoedRuSZyNWGGNEzLs.jpg?scale-down-to=1024",
  },
  {
    id: 4,
    order: 4,
    name: "Google",
    details: "Web, Product",
    year: 2024,
    image: "https://framerusercontent.com/images/Wf6XfdIKDSduOjZwiHHIO1Jp8U.jpg?scale-down-to=1024",
  },
  {
    id: 5,
    order: 5,
    name: "Harvard",
    details: "Brand, Web, Product",
    year: 2025,
    image: "https://framerusercontent.com/images/EGCY2shnjWtz3nE6PtBundg6vkM.jpg?scale-down-to=1024",
  },
  {
    id: 6,
    order: 6,
    name: "Neon Horizons",
    details: "Brand, Product",
    year: 2025,
    image: "https://framerusercontent.com/images/WtDkhEjQ1TNDVDYNkBVhFoJnfU.jpg?scale-down-to=1024",
  },
];
